--- # My First Playbook
 - hosts: local
   remote_user: ansible
   become: yes
   tasks: 
   - name: Confirm User
     user:
      name: kart
      state: absent
     notify : test_one
         
   handlers:
   - name: test_one
     service:
      name: httpd
      state: stopped
