--- # MOD Playbook
 - hosts: boa
   remote_user: ansible
   become: yes
   connection: ssh
   vars:
     motd_value: "{{ lookup('file','/tmp/abc.txt') }}"
   tasks:
     - debug:
         msg= {{motd_value}}
