--- # My First Playbook
 - hosts: boa 
   remote_user: ansible
   become: yes
   tasks:
   - name: Installing Apache on nodes
     yum:
      name: httpd
      state: latest
   - name: Restarting the Appache SErvice
     service: 
      name: httpd
      state: restarted
